### PR TITLE
allow munging both Makefile.PL and Build.PL

### PR DESCRIPTION
**Pull request by karenetheridge**
(issue fixed; tests pass)

### CODE REVIEW

**Comment by karenetheridge** [comment]
It looks like the 5.8.8 travis build failed because travis can't find that perl version anymore. Maybe just specify it in the config as "5.8"?

**Comment by xdg** [comment]
That's just travis complaining before the travis helpers kick in.  Problem is [here](https://travis-ci.org/dagolden/Dist-Zilla-Plugin-OSPrereqs/jobs/159214720#L4393):

```
t/osprereqs-multi.t ... Can't locate Dist/Zilla/Tester.pm in @INC (@INC contains: t/lib /home/travis/build/dagolden/Dist-Zilla-Plugin-OSPrereqs/blib/lib /home/travis/build/dagolden/Dist-Zilla-Plugin-OSPrereqs/blib/arch /home/travis/perl5/perlbrew/perls/5.8.8/lib/5.8.8/x86_64-linux /home/travis/perl5/perlbrew/perls/5.8.8/lib/5.8.8 /home/travis/perl5/perlbrew/perls/5.8.8/lib/site_perl/5.8.8/x86_64-linux /home/travis/perl5/perlbrew/perls/5.8.8/lib/site_perl/5.8.8 /home/travis/perl5/perlbrew/perls/5.8.8/lib/site_perl .) at t/lib/Test/DZil.pm line 6.
```

**Comment by xdg** [comment]
And that's a problem because DZ bumped to 5.14.

**Comment by xdg** [comment]
Rebased to master and merged.

**Pull request closed without merging**
